### ISSUE TITLE
Match any command case

### ISSUE THREAD

**Issue by TranchedepainLeMeilleurSurDuckhunt** [DuckHunt-discord/DHV3#8]
!shop = !Shop = !sHop etc...
Peu importe la façon dont c'est écrit du moment que c'est shop faudrait que la commande soit validée

**Comment by Diagamma** [comment]
go demander si ça pourrait être ajouté o/

**Comment by Olpouin** [comment]
Rofl le "No" magnifique

**Comment by Diagamma** [comment]
https://github.com/Rapptz/discord.py/issues/466
je fais ça demain

**Comment by Diagamma** [comment]
Oh, my bad, c'est pour le rewrite de discord.py. J'attendrai que ça sorte alors. o/

**Comment by Diagamma** [comment]
J'ai bien compris, je disais que j'implémenterai le petit bout de code une fois qu'on utilisera le rewrite de discord.py.
